title: Jekyll Blog Demo
description: Starter for a static website or blog - built with Jekyll, a minimal theme and GH Pages

url: https://michaelcurrin.github.io
baseurl: /jekyll-blog-demo

exclude:
  - README.md