title: Jekyll Blog Demo
description: Starter for a static website or blog - built with Jekyll, a minimal theme and GH Pages

url: https://koodattu.github.io
baseurl: /jekyll-blog-testing

exclude:
  - jbt
  - jbt/